In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 10, dtype='int8')
arr2 = arr.copy()

In [4]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int8)

In [5]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int8)

In [6]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int8)

In [7]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int8)

In [12]:
matriz = arr.reshape(2, 5)
matriz2 = matriz.copy()

In [13]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]], dtype=int8)

In [14]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]], dtype=int8)

In [16]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int8)

In [17]:
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int8)

In [18]:
np.matmul(matriz, matriz2.T)

array([[30, 80],
       [80, -1]], dtype=int8)

In [ ]:
matriz @ matriz2.T