In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 10, (3, 2))

In [3]:
arr.shape

(3, 2)

In [4]:
arr

array([[8, 7],
       [2, 6],
       [4, 9]])

In [5]:
arr.reshape(1, 6)

array([[8, 7, 2, 6, 4, 9]])

Para que el reshape funcione, debes de asegurarte que los numeros multiplicados den el mismo valor

In [6]:
arr.reshape(2, 3)

array([[8, 7, 2],
       [6, 4, 9]])